/* istanbul ignore file */
import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from "@/styles/home.module.css";
import Header from '@/components/header';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={inter.className}>
        <Header />
        <main className={styles.main}>
          <h1 className={styles.title}>
            Cuidamos bem do seu pokémon, para ele cuidar bem de você
          </h1>
        </main>
      </div>
    </>
  )
}
