/* istanbul ignore file */
import Head from 'next/head'
import Nav from '@/components/nav'
import Header from '@/components/header'
import Modal, { ModalProps } from '@/components/modal'
import styles from '@/styles/feedback.module.css';
import { useRouter } from 'next/router';

export default function Feedback() {
  const router = useRouter();

  const feedback = router.query.feedback as ModalProps['kind']
  const title = router.query.title as string
  const subtitle = router.query.subtitle as string

  return (
    <>
      <Head>
        <title>Feedback</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Header />
        <main className={styles.main}>
          <Nav
            title='Agendar consulta'
            subtitle='Recupere seus pokémons em 5 segundos'
            breadcrumb={['Home', 'Agendar consulta']}
          />
          <Modal
            title={title}
            subtitle={subtitle}
            kind={feedback}
          />
        </main>
      </div>
    </>
  )
}
